language: node_js
node_js:
  - "6.10.3"
cache:
  directories:
  - node_modules
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      npm run build;
      export BUCKET=project-elephant;
    else
      npm run build-dev;
      export BUCKET=project-elephant-dev;
    fi
deploy:
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $BUCKET
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
  region: $AWS_DEFAULT_REGION