language: node_js
node_js:
  - "6.10.3"
cache: pip
  directories:
  - node_modules
install:
  - pip install --user awscli
script:
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: project-elephant
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"